### ISSUE TITLE
Not sure if this is an issue

### ISSUE THREAD

**Issue by TG-one** [silphid/silphid.unity#3]
I was looking for some Unity Scene transitions and came across this and it looked interesting.  Downloaded, unzipped and opened it in Unity 2017.1.1f1
 - Unity warned me that this was last opened with Unity 2017.2 and I could have problems
 - When it opened I received 47 errors such as 
"Assets/Examples/Sequencit/Sequencing1.cs(3,15): error CS0234: The type or namespace name `Extensions' does not exist in the namespace `Silphid'. Are you missing an assembly reference?"

"Assets/Examples/Sequencit/Sequencing1.cs(4,15): error CS0234: The type or namespace name `Sequencit' does not exist in the namespace `Silphid'. Are you missing an assembly reference?"

"Assets/Examples/Sequencit/Sequencing1.cs(6,7): error CS0246: The type or namespace name `UniRx' could not be found. Are you missing an assembly reference?"

"Assets/Examples/Showzup/Application/AppInstaller.cs(1,7): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?"

Essentially the following could not be found:
 - namespace name `Extensions'
 - namespace name `Sequencit'
 - namespace name `UniRx'
 - namespace name `log4net'
 - namespace name `Loadzup'
 - namespace name `Injexit'
 -  namespace name `RootInstaller'
 - namespace name `Variant'
 - namespace name `ViewModel'
 - namespace name `View'
 -  namespace name `IInjectionAdapter'
 - namespace name `SerialDisposable'
 - namespace name `BoolReactiveProperty'
 - namespace name `Unit'
 - namespace name `ILog'
 - namespace name `Manifest'
 - namespace name `NavigationControl'
 - namespace name `SelectionControl'
 - namespace name `IContainer'

plus the following:
Assets/Examples/Showzup/Application/AppInstaller.cs(28,33): error CS0115: `App.AppInstaller.Configure()' is marked as an override but no suitable method found to override

Assets/Examples/Showzup/Application/AppInstaller.cs(105,33): error CS0115: `App.AppInstaller.Complete()' is marked as an override but no suitable method found to override

Not sure if I did something wrong, but I gave up.  I will leave it to you to figure this out.
Let me know if I missed doing something.

Regards,

**Comment by silphid** [comment]
Hello TG-one!

You seem to be using a very outdated version of the framework. I just released yesterday the first production-ready version of the framework (v2017.3.1), which should be much easier to setup and use:
https://github.com/silphid/silphid.unity/releases/latest

There is also a new documentation website here, with improved setup instructions:
http://silphid.com/silphid.unity/

If you are looking for a system to transition between arbitrary scenes, this might not be the solution your are looking for. The transition system in *Silphid.Unity* is intended to transition between different UI pages, not arbitrary scenes with 3D object.

Hope this helps! :)
Regards,
Mathieu
