### ISSUE TITLE
Sample Project Missing InjectionAdapter Concrete Class

### ISSUE THREAD

**Issue by allan-within** [Silphid/Silphid.Unity#4]
<img width="1078" alt="screen shot 2017-12-15 at 9 58 29 am" src="https://user-images.githubusercontent.com/33072322/34054163-89f9b460-e17e-11e7-8326-ebc269817197.png">

One of the first thing the app does is try to bind IInjectionAdapter to InjectionAdapter - which isn't included any more in the project. I dropped in the Integrations/Showzup/Injexit/InjectionAdpater.cs file from an old build of the sample project, and that seemed to fix the issue. 

Presumably you were moving things around and forgot to include this?

**Comment by silphid** [comment]
Thanks Allan for raising this issue.  I just fixed it, along with another issue and submitted a new release `2017.3.2`.

Regards,
Mathieu
